import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="px-6 py-2.5 bg-white dark:bg-slate-900">
            <div className="flex items-center justify-between max-w-7xl m-auto">
              <Link href="/" className="font-bold">TrueDamage.gg</Link>
              <Navbar />
              <ModeToggle />
            </div>
          </header>

          <main>
            {children}
          </main>

          <footer>

          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
